# Configuración del sitio
title: DTL
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/freelinuxdistrodeployed/"
url: ""
twitter_username:
github_username:  freelinuxdistrodeployed/freelinuxdistrodeployed
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
