# Configuración del sitio
title: LDT
email:
description: "Linux Deployed Tool"
baseurl: "/LDT"
url: ""
twitter_username:
github_username:  freelinuxdistrodeployed/LDT
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
