# Configuración del sitio
title: DTL
email:
description: ""
baseurl: "/freelinuxdistrodeployed"
url: ""
twitter_username:
github_username:  freelinuxdistrodeployed/freelinuxdistrodeployed
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
