---
#Despliegue de configuración de todos los equipos:

- name: Aplicación de la configuración general
  sudo: true
  hosts: all
  remote_user: root

  roles:
    - common

#Específico a los equipos de administración

- name: Aplicación de configuracion a los host de administracion
  sudo: true
  hosts: admin
  remote_user: root

  roles:
    - admin



