---
- hosts: all
  sudo: true
  vars:
    usuario: 'ansibleUser'
    password: '1122334455'
  tasks:
  - name: Creacion de usuario
    command: useradd -m {{ usuario }} creates=/home/{{ usuario }}
    sudo: true

  - name: Configuracion password
    shell: usermod -p $(echo '{{ password }}' | openssl passwd -1 -stdin) {{ usuario }}
    sudo: true
 
 
